# Generated by Django 3.1.7 on 2021-04-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=30, verbose_name='Отчество (если таковое имеется)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('workTime', models.IntegerField(verbose_name='Время выполнения (мин)')),
                ('questions_count', models.IntegerField(verbose_name='Количество вопросов')),
                ('answer_count', models.IntegerField(verbose_name='Количество ответов на каждый вопрос')),
                ('statisfactorily', models.IntegerField(verbose_name='Удовлетворительно')),
                ('good', models.IntegerField(verbose_name='Хорошо')),
                ('perfect', models.IntegerField(verbose_name='Отлично')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.department', verbose_name='Кафедра')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Описание тестов',
                'verbose_name_plural': 'Описание тестов',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, verbose_name='ФИО')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время завершения')),
                ('rating', models.FloatField(verbose_name='Проценты')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('weight', models.FloatField(default=1, verbose_name='Вес')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст ответа')),
                ('is_right', models.BooleanField(verbose_name='Верно/Неверно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
    ]
