# Generated by Django 3.1.7 on 2021-04-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='second_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='third_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество (если таковое имеется)'),
        ),
    ]
