# Generated by Django 3.1.7 on 2021-04-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210401_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='workTime',
            new_name='work_time',
        ),
    ]
