# Generated by Django 3.1.7 on 2021-04-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210401_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_count',
            field=models.IntegerField(default=1, verbose_name='Количество ответов на каждый вопрос'),
        ),
        migrations.AlterField(
            model_name='test',
            name='good',
            field=models.IntegerField(default=1, verbose_name='Хорошо'),
        ),
        migrations.AlterField(
            model_name='test',
            name='perfect',
            field=models.IntegerField(default=1, verbose_name='Отлично'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions_count',
            field=models.IntegerField(default=1, verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='statisfactorily',
            field=models.IntegerField(default=1, verbose_name='Удовлетворительно'),
        ),
        migrations.AlterField(
            model_name='test',
            name='work_time',
            field=models.IntegerField(default=1, verbose_name='Время выполнения (мин)'),
        ),
    ]
