# Generated by Django 3.1.7 on 2021-04-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
