# Generated by Django 3.1.7 on 2021-04-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_teacher_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='user',
        ),
    ]
