# Generated by Django 3.2 on 2021-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20210414_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='difficluty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='', max_length=6),
        ),
    ]
