# Generated by Django 3.2 on 2021-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_rename_statisfactorily_test_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'легко'), ('medium', 'средне'), ('hard', 'тяжело')], default='', max_length=6, verbose_name='Сложность'),
        ),
    ]
