# Generated by Django 3.2 on 2021-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_alter_test_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=1, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1, null=True, verbose_name='Вес'),
        ),
    ]
