# Generated by Django 3.2 on 2021-04-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_question_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default='default', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=1, null=True, verbose_name='количсество ответов на данный вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default='default', null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
    ]
